/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/solutions": {
    /** Get solutions for tasks */
    get: {
      parameters: {
        query: {
          /** @description Filter by task IDs */
          taskIDs: string[];
        };
      };
      responses: {
        /** @description Successful retrieval */
        200: {
          content: {
            "application/json": components["schemas"]["ProblemSolution"][];
          };
        };
      };
    };
    /** Submit a solution */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProblemSolution"][];
        };
      };
      responses: {
        /** @description Successful submission */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProblemSolution: {
      taskId: components["schemas"]["TaskId"];
      solution: string[];
      isCorrect: boolean;
    };
    TaskId: string;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
