---
version: "3.7"

# golang application and redis

services:
  api:
    image: ghcr.io/moleus/collective-edu:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - GIN_MODE=release
    networks:
      - backend
    user: "1000:1000"
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    command:
      - sh
      - -c
      - redis-server --appendonly yes --maxmemory $$(( 1024 * 1024 * 256 )) --maxmemory-policy volatile-lru  # 256MB
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    user: "1000:1000"
    networks:
      - backend
    volumes:
      - /opt/redis-storage:/data
    deploy:
      resources:
        limits:
          memory: 256m

networks:
  backend:
    driver: bridge
