version: "3.7"

# golang application and redis

services:
  api:
    image: ghcr.io/moleus/collective-edu:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - backend
    volumes:
      - /opt/redis-storage:/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command:
      - bash
      - -c
      - redis-server --appendonly yes --maxmemory $$(( $$( cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || cat /sys/fs/cgroup/memory.max ) - 100000000)) --maxmemory-policy volatile-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 100m

networks:
    backend:
        driver: bridge
